// Centralized menu items list for subscription feature management
// This should match the menu items in sidebar.tsx

export const ALL_MENU_ITEMS = [
  'dashboard',
  'products',
  'customers',
  'shortcuts',
  'tasks',
  'leads',
  'lead-types',
  'lead-sync',
  'social-integrations',
  'lead-analytics',
  'calendar',
  // 'bookings',
  'packages',
  'invoices',
  'estimates',
  'vendors',
  'expenses',
  'booking-recommendations',
  'email-campaigns',
  'email-automations',
  'email-ab-tests',
  'email-segments',
  'email-settings',
  'email-test',
  'gmail-emails',
  // 'hotels',
  // 'hotels-list',
  'automation-workflows',
  'reports',
  'users',
  'roles',
  'dynamic-fields',
  'menu-ordering',
  'settings',
  'subscription',
  'support',
] as const;

export const MENU_ITEM_LABELS: Record<string, string> = {
  'dashboard': 'Dashboard',
  'products': "Product Management",
  'customers': 'Customer Directory',
  'shortcuts': 'Quick Shortcuts',
  'tasks': 'Tasks & Follow-ups',
  'leads': 'Lead Pipeline',
  'lead-types': 'Lead Categories',
  'lead-sync': 'Lead Import & Sync',
  'social-integrations': 'Social Media Hub',
  'lead-analytics': 'Lead Analytics',
  'calendar': 'Calendar',
  // 'bookings': 'Booking Management',
  // 'packages': 'Travel Packages',
  'invoices': 'Invoices & Billing',
  'estimates': 'Estimate Management',
  'vendors': 'Vendor Management',
  'expenses': 'Expense Management',
  // 'booking-recommendations': 'AI Recommendations',
  'email-campaigns': 'Campaign Manager',
  'email-automations': 'Email Workflows',
  'email-ab-tests': 'A/B Testing',
  'email-segments': 'Audience Segments',
  'email-settings': 'Email Configuration',
  'email-test': 'Email Testing',
  'gmail-emails': 'Gmail Integration',
  // 'hotels': 'Hotels Overview',
  // 'hotels-list': 'Flights',
  'automation-workflows': 'Workflow Automation',
  'reports': 'Analytics & Reports',
  'users': 'Users',
  'roles': 'Roles',
  'dynamic-fields': 'Dynamic Fields',
  'menu-ordering': 'Menu Customization',
  'settings': 'System Settings',
  'subscription': 'Subscription Plans',
  'support': 'Help & Support',
};

// Page routes mapping (for page-level access control)
export const PAGE_ROUTES: Record<string, string> = {
  'dashboard': '/dashboard',
  'product': '/products',
  'customers': '/customers',
  'shortcuts': '/shortcuts',
  'tasks': '/tasks',
  'leads': '/leads',
  'lead-types': '/lead-types',
  'lead-sync': '/lead-sync',
  'social-integrations': '/social-integrations',
  'lead-analytics': '/lead-analytics',
  'calendar': '/calendar',
  'bookings': '/bookings',
  'packages': '/packages',
  'invoices': '/invoices',
  'estimates': '/estimates',
  'vendors': '/vendors',
  'expenses': '/expenses',
  // 'booking-recommendations': '/booking-recommendations',
  'email-campaigns': '/email-campaigns',
  'email-automations': '/email-automations',
  'email-ab-tests': '/email-ab-tests',
  'email-segments': '/email-segments',
  'email-settings': '/email-settings',
  'email-test': '/email-test',
  'gmail-emails': '/gmail-emails',
  // 'hotels': '/hotels',
  // 'hotels-list': '/flights',
  'automation-workflows': '/automation-workflows',
  'reports': '/reports',
  'users': '/users',
  'roles': '/roles',
  'dynamic-fields': '/dynamic-fields',
  'menu-ordering': '/menu-ordering',
  'settings': '/settings',
  'subscription': '/subscription',
  'support': '/support',
};

// Country codes and currencies
export const COUNTRIES = [
  { code: 'US', name: 'United States', currency: 'USD' },
  { code: 'IN', name: 'India', currency: 'INR' },
  { code: 'GB', name: 'United Kingdom', currency: 'GBP' },
  { code: 'CA', name: 'Canada', currency: 'CAD' },
  { code: 'AU', name: 'Australia', currency: 'AUD' },
  { code: 'DE', name: 'Germany', currency: 'EUR' },
  { code: 'FR', name: 'France', currency: 'EUR' },
  { code: 'IT', name: 'Italy', currency: 'EUR' },
  { code: 'ES', name: 'Spain', currency: 'EUR' },
  { code: 'NL', name: 'Netherlands', currency: 'EUR' },
  { code: 'BR', name: 'Brazil', currency: 'BRL' },
  { code: 'MX', name: 'Mexico', currency: 'MXN' },
  { code: 'JP', name: 'Japan', currency: 'JPY' },
  { code: 'CN', name: 'China', currency: 'CNY' },
  { code: 'SG', name: 'Singapore', currency: 'SGD' },
  { code: 'AE', name: 'United Arab Emirates', currency: 'AED' },
  { code: 'SA', name: 'Saudi Arabia', currency: 'SAR' },
];

