// Country, State, and City data for location dropdowns
export const countries = [
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
];

export const statesData: Record<string, Array<{ code: string; name: string }>> = {
  US: [
    { code: 'AL', name: 'Alabama' },
    { code: 'AK', name: 'Alaska' },
    { code: 'AZ', name: 'Arizona' },
    { code: 'AR', name: 'Arkansas' },
    { code: 'CA', name: 'California' },
    { code: 'CO', name: 'Colorado' },
    { code: 'CT', name: 'Connecticut' },
    { code: 'DE', name: 'Delaware' },
    { code: 'FL', name: 'Florida' },
    { code: 'GA', name: 'Georgia' },
    { code: 'HI', name: 'Hawaii' },
    { code: 'ID', name: 'Idaho' },
    { code: 'IL', name: 'Illinois' },
    { code: 'IN', name: 'Indiana' },
    { code: 'IA', name: 'Iowa' },
    { code: 'KS', name: 'Kansas' },
    { code: 'KY', name: 'Kentucky' },
    { code: 'LA', name: 'Louisiana' },
    { code: 'ME', name: 'Maine' },
    { code: 'MD', name: 'Maryland' },
    { code: 'MA', name: 'Massachusetts' },
    { code: 'MI', name: 'Michigan' },
    { code: 'MN', name: 'Minnesota' },
    { code: 'MS', name: 'Mississippi' },
    { code: 'MO', name: 'Missouri' },
    { code: 'MT', name: 'Montana' },
    { code: 'NE', name: 'Nebraska' },
    { code: 'NV', name: 'Nevada' },
    { code: 'NH', name: 'New Hampshire' },
    { code: 'NJ', name: 'New Jersey' },
    { code: 'NM', name: 'New Mexico' },
    { code: 'NY', name: 'New York' },
    { code: 'NC', name: 'North Carolina' },
    { code: 'ND', name: 'North Dakota' },
    { code: 'OH', name: 'Ohio' },
    { code: 'OK', name: 'Oklahoma' },
    { code: 'OR', name: 'Oregon' },
    { code: 'PA', name: 'Pennsylvania' },
    { code: 'RI', name: 'Rhode Island' },
    { code: 'SC', name: 'South Carolina' },
    { code: 'SD', name: 'South Dakota' },
    { code: 'TN', name: 'Tennessee' },
    { code: 'TX', name: 'Texas' },
    { code: 'UT', name: 'Utah' },
    { code: 'VT', name: 'Vermont' },
    { code: 'VA', name: 'Virginia' },
    { code: 'WA', name: 'Washington' },
    { code: 'WV', name: 'West Virginia' },
    { code: 'WI', name: 'Wisconsin' },
    { code: 'WY', name: 'Wyoming' },
  ],
  IN: [
    { code: 'AP', name: 'Andhra Pradesh' },
    { code: 'AR', name: 'Arunachal Pradesh' },
    { code: 'AS', name: 'Assam' },
    { code: 'BR', name: 'Bihar' },
    { code: 'CG', name: 'Chhattisgarh' },
    { code: 'GA', name: 'Goa' },
    { code: 'GJ', name: 'Gujarat' },
    { code: 'HR', name: 'Haryana' },
    { code: 'HP', name: 'Himachal Pradesh' },
    { code: 'JK', name: 'Jammu and Kashmir' },
    { code: 'JH', name: 'Jharkhand' },
    { code: 'KA', name: 'Karnataka' },
    { code: 'KL', name: 'Kerala' },
    { code: 'MP', name: 'Madhya Pradesh' },
    { code: 'MH', name: 'Maharashtra' },
    { code: 'MN', name: 'Manipur' },
    { code: 'ML', name: 'Meghalaya' },
    { code: 'MZ', name: 'Mizoram' },
    { code: 'NL', name: 'Nagaland' },
    { code: 'OD', name: 'Odisha' },
    { code: 'PB', name: 'Punjab' },
    { code: 'RJ', name: 'Rajasthan' },
    { code: 'SK', name: 'Sikkim' },
    { code: 'TN', name: 'Tamil Nadu' },
    { code: 'TS', name: 'Telangana' },
    { code: 'TR', name: 'Tripura' },
    { code: 'UP', name: 'Uttar Pradesh' },
    { code: 'UK', name: 'Uttarakhand' },
    { code: 'WB', name: 'West Bengal' },
    { code: 'AN', name: 'Andaman and Nicobar Islands' },
    { code: 'CH', name: 'Chandigarh' },
    { code: 'DN', name: 'Dadra and Nagar Haveli' },
    { code: 'DD', name: 'Daman and Diu' },
    { code: 'DL', name: 'Delhi' },
    { code: 'LD', name: 'Lakshadweep' },
    { code: 'PY', name: 'Puducherry' },
  ],
  CA: [
    { code: 'AB', name: 'Alberta' },
    { code: 'BC', name: 'British Columbia' },
    { code: 'MB', name: 'Manitoba' },
    { code: 'NB', name: 'New Brunswick' },
    { code: 'NL', name: 'Newfoundland and Labrador' },
    { code: 'NS', name: 'Nova Scotia' },
    { code: 'NT', name: 'Northwest Territories' },
    { code: 'NU', name: 'Nunavut' },
    { code: 'ON', name: 'Ontario' },
    { code: 'PE', name: 'Prince Edward Island' },
    { code: 'QC', name: 'Quebec' },
    { code: 'SK', name: 'Saskatchewan' },
    { code: 'YT', name: 'Yukon' },
  ],
  AU: [
    { code: 'ACT', name: 'Australian Capital Territory' },
    { code: 'NSW', name: 'New South Wales' },
    { code: 'NT', name: 'Northern Territory' },
    { code: 'QLD', name: 'Queensland' },
    { code: 'SA', name: 'South Australia' },
    { code: 'TAS', name: 'Tasmania' },
    { code: 'VIC', name: 'Victoria' },
    { code: 'WA', name: 'Western Australia' },
  ],
  GB: [
    { code: 'ENG', name: 'England' },
    { code: 'SCT', name: 'Scotland' },
    { code: 'WAL', name: 'Wales' },
    { code: 'NIR', name: 'Northern Ireland' },
  ],
};

// Sample cities data for major states/provinces
export const citiesData: Record<string, Array<{ name: string; state: string }>> = {
  'US-CA': [
    { name: 'Los Angeles', state: 'CA' },
    { name: 'San Francisco', state: 'CA' },
    { name: 'San Diego', state: 'CA' },
    { name: 'Sacramento', state: 'CA' },
    { name: 'San Jose', state: 'CA' },
    { name: 'Fresno', state: 'CA' },
    { name: 'Oakland', state: 'CA' },
    { name: 'Santa Ana', state: 'CA' },
  ],
  'US-NY': [
    { name: 'New York City', state: 'NY' },
    { name: 'Buffalo', state: 'NY' },
    { name: 'Rochester', state: 'NY' },
    { name: 'Yonkers', state: 'NY' },
    { name: 'Syracuse', state: 'NY' },
    { name: 'Albany', state: 'NY' },
    { name: 'New Rochelle', state: 'NY' },
    { name: 'Mount Vernon', state: 'NY' },
  ],
  'US-TX': [
    { name: 'Houston', state: 'TX' },
    { name: 'San Antonio', state: 'TX' },
    { name: 'Dallas', state: 'TX' },
    { name: 'Austin', state: 'TX' },
    { name: 'Fort Worth', state: 'TX' },
    { name: 'El Paso', state: 'TX' },
    { name: 'Arlington', state: 'TX' },
    { name: 'Corpus Christi', state: 'TX' },
  ],
  'US-FL': [
    { name: 'Jacksonville', state: 'FL' },
    { name: 'Miami', state: 'FL' },
    { name: 'Tampa', state: 'FL' },
    { name: 'Orlando', state: 'FL' },
    { name: 'St. Petersburg', state: 'FL' },
    { name: 'Hialeah', state: 'FL' },
    { name: 'Tallahassee', state: 'FL' },
    { name: 'Fort Lauderdale', state: 'FL' },
  ],
  'IN-MH': [
    { name: 'Mumbai', state: 'MH' },
    { name: 'Pune', state: 'MH' },
    { name: 'Nagpur', state: 'MH' },
    { name: 'Nashik', state: 'MH' },
    { name: 'Aurangabad', state: 'MH' },
    { name: 'Solapur', state: 'MH' },
    { name: 'Amravati', state: 'MH' },
    { name: 'Kolhapur', state: 'MH' },
  ],
  'IN-DL': [
    { name: 'New Delhi', state: 'DL' },
    { name: 'Central Delhi', state: 'DL' },
    { name: 'North Delhi', state: 'DL' },
    { name: 'South Delhi', state: 'DL' },
    { name: 'East Delhi', state: 'DL' },
    { name: 'West Delhi', state: 'DL' },
    { name: 'North East Delhi', state: 'DL' },
    { name: 'North West Delhi', state: 'DL' },
  ],
  'IN-KA': [
    { name: 'Bangalore', state: 'KA' },
    { name: 'Mysore', state: 'KA' },
    { name: 'Hubli', state: 'KA' },
    { name: 'Mangalore', state: 'KA' },
    { name: 'Belgaum', state: 'KA' },
    { name: 'Gulbarga', state: 'KA' },
    { name: 'Davanagere', state: 'KA' },
    { name: 'Bellary', state: 'KA' },
  ],
  'IN-TN': [
    { name: 'Chennai', state: 'TN' },
    { name: 'Coimbatore', state: 'TN' },
    { name: 'Madurai', state: 'TN' },
    { name: 'Tiruchirappalli', state: 'TN' },
    { name: 'Salem', state: 'TN' },
    { name: 'Tirunelveli', state: 'TN' },
    { name: 'Tiruppur', state: 'TN' },
    { name: 'Vellore', state: 'TN' },
  ],
  'CA-ON': [
    { name: 'Toronto', state: 'ON' },
    { name: 'Ottawa', state: 'ON' },
    { name: 'Hamilton', state: 'ON' },
    { name: 'London', state: 'ON' },
    { name: 'Kitchener', state: 'ON' },
    { name: 'Windsor', state: 'ON' },
    { name: 'Oshawa', state: 'ON' },
    { name: 'Barrie', state: 'ON' },
  ],
  'CA-BC': [
    { name: 'Vancouver', state: 'BC' },
    { name: 'Victoria', state: 'BC' },
    { name: 'Surrey', state: 'BC' },
    { name: 'Burnaby', state: 'BC' },
    { name: 'Richmond', state: 'BC' },
    { name: 'Abbotsford', state: 'BC' },
    { name: 'Coquitlam', state: 'BC' },
    { name: 'Kelowna', state: 'BC' },
  ],
  'AU-NSW': [
    { name: 'Sydney', state: 'NSW' },
    { name: 'Newcastle', state: 'NSW' },
    { name: 'Central Coast', state: 'NSW' },
    { name: 'Wollongong', state: 'NSW' },
    { name: 'Maitland', state: 'NSW' },
    { name: 'Albury', state: 'NSW' },
    { name: 'Wagga Wagga', state: 'NSW' },
    { name: 'Port Macquarie', state: 'NSW' },
  ],
  'AU-VIC': [
    { name: 'Melbourne', state: 'VIC' },
    { name: 'Geelong', state: 'VIC' },
    { name: 'Ballarat', state: 'VIC' },
    { name: 'Bendigo', state: 'VIC' },
    { name: 'Shepparton', state: 'VIC' },
    { name: 'Warrnambool', state: 'VIC' },
    { name: 'Wodonga', state: 'VIC' },
    { name: 'Traralgon', state: 'VIC' },
  ],
};

// Default lead type templates with pre-configured fields
export const defaultLeadTypes = [
  {
    name: 'Flight',
    description: 'Flight booking inquiries and reservations',
    icon: 'Plane',
    color: '#3B82F6',
    fields: [
      { fieldName: 'departureDate', fieldLabel: 'Departure Date', fieldType: 'date', isRequired: true, displayOrder: 1 },
      { fieldName: 'returnDate', fieldLabel: 'Return Date', fieldType: 'date', isRequired: false, displayOrder: 2 },
      { fieldName: 'departureCity', fieldLabel: 'From City', fieldType: 'text', isRequired: true, displayOrder: 3 },
      { fieldName: 'arrivalCity', fieldLabel: 'To City', fieldType: 'text', isRequired: true, displayOrder: 4 },
      { fieldName: 'passengers', fieldLabel: 'Number of Passengers', fieldType: 'number', isRequired: true, displayOrder: 5 },
      { fieldName: 'classPreference', fieldLabel: 'Class Preference', fieldType: 'select', fieldOptions: ['Economy', 'Premium Economy', 'Business', 'First Class'], displayOrder: 6 },
      { fieldName: 'tripType', fieldLabel: 'Trip Type', fieldType: 'select', fieldOptions: ['One Way', 'Round Trip', 'Multi City'], isRequired: true, displayOrder: 7 },
      { fieldName: 'airlinePreference', fieldLabel: 'Preferred Airlines', fieldType: 'text', displayOrder: 8 },
      { fieldName: 'budgetRange', fieldLabel: 'Budget Range', fieldType: 'select', fieldOptions: ['Under $500', '$500-$1000', '$1000-$2000', '$2000-$5000', 'Above $5000'], displayOrder: 9 },
    ]
  },
  {
    name: 'Hotel',
    description: 'Hotel booking and accommodation inquiries',
    icon: 'Building2',
    color: '#10B981',
    fields: [
      { fieldName: 'checkInDate', fieldLabel: 'Check-in Date', fieldType: 'date', isRequired: true, displayOrder: 1 },
      { fieldName: 'checkOutDate', fieldLabel: 'Check-out Date', fieldType: 'date', isRequired: true, displayOrder: 2 },
      { fieldName: 'destination', fieldLabel: 'Destination', fieldType: 'text', isRequired: true, displayOrder: 3 },
      { fieldName: 'guests', fieldLabel: 'Number of Guests', fieldType: 'number', isRequired: true, displayOrder: 4 },
      { fieldName: 'rooms', fieldLabel: 'Number of Rooms', fieldType: 'number', isRequired: true, displayOrder: 5 },
      { fieldName: 'roomType', fieldLabel: 'Room Type', fieldType: 'select', fieldOptions: ['Standard', 'Deluxe', 'Suite', 'Presidential Suite'], displayOrder: 6 },
      { fieldName: 'hotelCategory', fieldLabel: 'Hotel Category', fieldType: 'select', fieldOptions: ['Budget (1-2 Star)', 'Mid-range (3 Star)', 'Luxury (4 Star)', 'Ultra Luxury (5 Star)'], displayOrder: 7 },
      { fieldName: 'specialRequests', fieldLabel: 'Special Requests', fieldType: 'textarea', displayOrder: 8 },
      { fieldName: 'budgetPerNight', fieldLabel: 'Budget per Night', fieldType: 'select', fieldOptions: ['Under $50', '$50-$100', '$100-$200', '$200-$500', 'Above $500'], displayOrder: 9 },
    ]
  },
  {
    name: 'Package',
    description: 'Complete travel package inquiries',
    icon: 'Package',
    color: '#8B5CF6',
    fields: [
      { fieldName: 'startDate', fieldLabel: 'Travel Start Date', fieldType: 'date', isRequired: true, displayOrder: 1 },
      { fieldName: 'endDate', fieldLabel: 'Travel End Date', fieldType: 'date', isRequired: true, displayOrder: 2 },
      { fieldName: 'destination', fieldLabel: 'Destination', fieldType: 'text', isRequired: true, displayOrder: 3 },
      { fieldName: 'travelers', fieldLabel: 'Number of Travelers', fieldType: 'number', isRequired: true, displayOrder: 4 },
      { fieldName: 'packageType', fieldLabel: 'Package Type', fieldType: 'select', fieldOptions: ['Honeymoon', 'Family Vacation', 'Adventure', 'Cultural', 'Business', 'Group Tour'], displayOrder: 5 },
      { fieldName: 'accommodation', fieldLabel: 'Accommodation Preference', fieldType: 'select', fieldOptions: ['Budget', 'Mid-range', 'Luxury', 'Ultra Luxury'], displayOrder: 6 },
      { fieldName: 'inclusions', fieldLabel: 'Required Inclusions', fieldType: 'textarea', placeholder: 'Flights, hotels, meals, activities, etc.', displayOrder: 7 },
      { fieldName: 'activities', fieldLabel: 'Preferred Activities', fieldType: 'textarea', displayOrder: 8 },
      { fieldName: 'totalBudget', fieldLabel: 'Total Budget', fieldType: 'select', fieldOptions: ['Under $1000', '$1000-$3000', '$3000-$5000', '$5000-$10000', 'Above $10000'], displayOrder: 9 },
    ]
  },
  {
    name: 'Events',
    description: 'Event planning and management inquiries',
    icon: 'Calendar',
    color: '#F59E0B',
    fields: [
      { fieldName: 'eventDate', fieldLabel: 'Event Date', fieldType: 'date', isRequired: true, displayOrder: 1 },
      { fieldName: 'eventType', fieldLabel: 'Event Type', fieldType: 'select', fieldOptions: ['Wedding', 'Corporate Event', 'Birthday Party', 'Anniversary', 'Conference', 'Exhibition', 'Other'], isRequired: true, displayOrder: 2 },
      { fieldName: 'venue', fieldLabel: 'Preferred Venue/Location', fieldType: 'text', displayOrder: 3 },
      { fieldName: 'attendees', fieldLabel: 'Number of Attendees', fieldType: 'number', isRequired: true, displayOrder: 4 },
      { fieldName: 'duration', fieldLabel: 'Event Duration', fieldType: 'select', fieldOptions: ['Half Day', 'Full Day', '2 Days', '3 Days', 'More than 3 Days'], displayOrder: 5 },
      { fieldName: 'services', fieldLabel: 'Required Services', fieldType: 'textarea', placeholder: 'Catering, decoration, entertainment, photography, etc.', displayOrder: 6 },
      { fieldName: 'theme', fieldLabel: 'Event Theme/Style', fieldType: 'text', displayOrder: 7 },
      { fieldName: 'budget', fieldLabel: 'Event Budget', fieldType: 'select', fieldOptions: ['Under $5000', '$5000-$15000', '$15000-$30000', '$30000-$50000', 'Above $50000'], displayOrder: 8 },
    ]
  },
  {
    name: 'Attraction',
    description: 'Tourist attractions and activity bookings',
    icon: 'MapPin',
    color: '#EF4444',
    fields: [
      { fieldName: 'visitDate', fieldLabel: 'Visit Date', fieldType: 'date', isRequired: true, displayOrder: 1 },
      { fieldName: 'attractionName', fieldLabel: 'Attraction/Activity Name', fieldType: 'text', displayOrder: 2 },
      { fieldName: 'location', fieldLabel: 'Location/City', fieldType: 'text', isRequired: true, displayOrder: 3 },
      { fieldName: 'visitors', fieldLabel: 'Number of Visitors', fieldType: 'number', isRequired: true, displayOrder: 4 },
      { fieldName: 'activityType', fieldLabel: 'Activity Type', fieldType: 'select', fieldOptions: ['Sightseeing', 'Adventure Sports', 'Cultural Tours', 'Food Tours', 'Museums', 'Theme Parks', 'Wildlife Safari', 'Water Sports'], displayOrder: 5 },
      { fieldName: 'timeSlot', fieldLabel: 'Preferred Time Slot', fieldType: 'select', fieldOptions: ['Morning', 'Afternoon', 'Evening', 'Full Day', 'Flexible'], displayOrder: 6 },
      { fieldName: 'groupType', fieldLabel: 'Group Type', fieldType: 'select', fieldOptions: ['Individual', 'Couple', 'Family with Kids', 'Friends Group', 'Corporate Group'], displayOrder: 7 },
      { fieldName: 'specialRequirements', fieldLabel: 'Special Requirements', fieldType: 'textarea', placeholder: 'Accessibility needs, dietary restrictions, etc.', displayOrder: 8 },
      { fieldName: 'budgetPerPerson', fieldLabel: 'Budget per Person', fieldType: 'select', fieldOptions: ['Under $50', '$50-$100', '$100-$200', '$200-$500', 'Above $500'], displayOrder: 9 },
    ]
  }
];